---
- name: Tap homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
  with_items:
    - "{{ homebrew_taps }}"

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
  with_items:
    - "{{ homebrew_installed_packages }}"

- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ homebrew_cask_apps }}"