---
- name: Create VSCode config
template:
  src: templates/vscode-settings.json.j2
  dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
  owner: "{{ lookup('env', 'USER') }}"
  force: yes

- name: Obtain path to vscode cli
  become: false
  local_action: command which code
  register: code_path

- name: Install my VSCode extensions
  shell: "{{ code_path.stdout }}" --install-extension {{ item }}
  with_items:
    - "{{ vscode_extensions }}"